version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: library/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - run: gem install bundler -v 1.17.3
      - run: bundle install
      - run: bundle exec rspec

workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["1.9.3", "2.0", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "3.0"]
