name: RSpec tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ruby:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
       include:
         - docker-image: 'silvioq/ruby-1.8.7'
           bundler-version: '1.17.3'
         - docker-image: 'library/ruby:1.9'
           bundler-version: '1.17.3'
         - docker-image: 'library/ruby:2.0'
           bundler-version: '1.17.3'
         - docker-image: 'library/ruby:2.2'
           bundler-version: '1.17.3'
         - docker-image: 'library/ruby:2.3'
         - docker-image: 'library/ruby:2.4'
         - docker-image: 'library/ruby:2.5'
         - docker-image: 'library/ruby:2.6'
         - docker-image: 'library/ruby:2.7'
         - docker-image: 'library/ruby:3.0'
         - docker-image: 'flavorjones/truffleruby:stable'
         - docker-image: 'bitnami/jruby:latest'
    container: ${{ matrix.docker-image }}
    steps:
    - uses: actions/checkout@v2
    - name: Install bundler ${{ matrix.bundler-version }}
      run: gem install bundler ${{ matrix.bundler-version && format('{0} {1}', '-v', matrix.bundler-version) || '' }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec
